spring:
  application:
    name: umusada-bank-service

  datasource:
    url: jdbc:postgresql://68.183.43.111:5432/umusada_db
    username: postgres
    password: P@ssword1
#    username: kimenyi
#    password: kImenyi@Ishyiga_2025!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  main:
    allow-circular-references: true
    allow-bean-definition: true

  jackson:
    default-property-inclusion: NON_NULL

server:
  port: 8088

logging:
  level:
    org.springframework: INFO
    org.hibernate.SQL: INFO  # Show SQL queries
    org.hibernate.type.descriptor.sql.BasicBinder: INFO  # Show SQL parameters